### PR TITLE
v1.0

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-:-LZ_1CiO6J-lBAgKtY9w:bweg3f8)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @aledj2, @Graeme-Smith, @NMNS93, and @woook)

**Review by aledj2 — CHANGES_REQUESTED** [review]
much better ways to fix the html issues than I came up with!

> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-:-LZ_Iovw1Orjs3XxL7uk:br23p6o)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @aledj2, @andyb3, @Graeme-Smith, @NMNS93, and @woook)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_IL4BEmIFBJ6Hg7ET:-LZ_IL4BEmIFBJ6Hg7EU:bqyuub0) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/README.md#L10)):*
> ```Markdown
> * pdfkit
> * Access to CIPAPI
> * JellyPy (in PYTHONPATH)
> ```

also needs wkhtmlpdfkit installed 
___
*[summary_findings.py, line 70 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_H2cLEmJ1PKvCmJfa:-LZ_H2cLEmJ1PKvCmJfb:b5e9934) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L70)):*
> ```Python
>                     sys.exit(f'response code {response.status_code}')
>             else:
>                 sys.exit(f'number of clinical reports {len(ir_details[0]["clinical_reports"])}')
> ```

Does this need to specify that this is a failure message?
___
*[summary_findings.py, line 72 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_Gwbp9FBc8Y7ng3aq:-LZ_Gwbz7Q14i8FkOeMo:b5e9934) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L72)):*
> ```Python
>                 sys.exit(f'number of clinical reports {len(ir_details[0]["clinical_reports"])}')
>         else:
>             sys.exit(f'number of interpretation requests {len(ir_details)}')
> ```

Does this need to specify that this is a failure message?
___
*[summary_findings.py, line 76 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_HSDX5PLPrb95ecC_:-LZ_HSDX5PLPrb95ecCa:b-6qz4nd) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L76)):*
> ```Python
>     def expand_coverage(self):
>         '''Expand the coverage section'''
>         # find the coverage div and delete so coverage seciton no longer needs to be clicked to be visible
> ```

typo but no need to change if this is the only change!
___
*[summary_findings.py, line 113 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_HrAV-js0-R8nOAx_:-LZ_HrAV-js0-R8nOAxa:bn60lwf) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L113)):*
> ```Python
>                     if col.get_text() == "Name":
>                         # prevent page breaks
>                         table['style'] = " page-break-inside: avoid !important"
> ```

could/should this be done to all tables, regardless of the column headers?
___
*[summary_findings.py, line 161 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_Ivbh2ss0PJ3kRAqW:-LZ_Ivbh2ss0PJ3kRAqX:b4dlan6) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L161)):*
> ```Python
>         # create dictionary of options that will be passed to the wkhtmltopdf command (see https://wkhtmltopdf.org/usage/wkhtmltopdf.txt for list of options)
>         options = {
>             'quiet': ''
> ```

are we going to add any page numbers or any footers?
___
*[summary_findings.py, line 174 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_IabA1mcxRweqk3kU:-LZ_IabBAFTOZkz77RUE:b-7p1070) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L174)):*
> ```Python
>     # Write out to a pdf
>     sof.fix_formatting()
>     sof.write_pdf(pdfreport_path=args.output_file, wkhtmltopdf='/usr/local/bin/wkhtmltopdf')
> ```

should wkhtmltopdf be a variable somewhere?

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @aledj2, @Graeme-Smith, @NMNS93, and @woook)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_IL4BEmIFBJ6Hg7ET:-LZdXwXz13RsUGInGoEs:b-896fix) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/README.md#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

also needs wkhtmlpdfkit installed 
</blockquote></details>

Done.
___
*[summary_findings.py, line 70 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_H2cLEmJ1PKvCmJfa:-LZdXxjp8MP18gnml8Au:b-896fix) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L70)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Does this need to specify that this is a failure message?
</blockquote></details>

Done.
___
*[summary_findings.py, line 72 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_Gwbp9FBc8Y7ng3aq:-LZdXy2r9IysG5BGJjuM:b-896fix) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L72)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Does this need to specify that this is a failure message?
</blockquote></details>

Done.
___
*[summary_findings.py, line 113 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_HrAV-js0-R8nOAx_:-LZdsBXh8BKcQoEudMPH:b-euiodv) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L113)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could/should this be done to all tables, regardless of the column headers?
</blockquote></details>

This doesn't work well for the coverage table because it is so long it has to split over pages, so think it's best to leave as is?
___
*[summary_findings.py, line 161 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_Ivbh2ss0PJ3kRAqW:-LZdYA_GBUGSUt3Ws8ni:b-896fix) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L161)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

are we going to add any page numbers or any footers?
</blockquote></details>

Done.
___
*[summary_findings.py, line 174 at r1](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-LZ_IabA1mcxRweqk3kU:-LZe39GzCqk9_CBMg8sO:b-896fix) ([raw file](https://github.com/moka-guys/100k_summary_findings_pdf/blob/68f7ddbf95cf6eace21b161822b586f8aa5f09f7/summary_findings.py#L174)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

should wkhtmltopdf be a variable somewhere?
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_summary_findings_pdf/1#-:-LZjVSOrCH5Xkka4KblC:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith, @NMNS93, and @woook)

**Pull request merged**
